apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: hive-operator-rolebinding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: hive-operator-role
subjects:
- kind: ServiceAccount
  name: hive-operator
  namespace: hive
