# NOTE: This binding uses the openshift apigroup as it is the only way to link
# to an openshift user group. This will not work if running hive on vanilla Kube,
# but the Hive operator will detect this and skip creation of the binding.
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: hive-admin
roleRef:
  name: hive-admin
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
groupNames:
- hive-admins
subjects:
- kind: Group
  name: hive-admins
